#ifndef SERVER_TEMPLATE_NS_H_
#define SERVER_TEMPLATE_NS_H_

#ifndef SERVER_TEMPLATE_NAMESPACE
#define SERVER_TEMPLATE_NAMESPACE server_template
#endif // !SERVER_TEMPLATE_NAMESPACE

#ifndef SERVER_TEMPLATE_NAMESPACE_BEGIN
#define SERVER_TEMPLATE_NAMESPACE_BEGIN namespace SERVER_TEMPLATE_NAMESPACE {
#endif // !SERVER_TEMPLATE_NAMESPACE_BEGIN

#ifndef SERVER_TEMPLATE_NAMESPACE_END
#define SERVER_TEMPLATE_NAMESPACE_END }
#endif // !SERVER_TEMPLATE_NAMESPACE_END

SERVER_TEMPLATE_NAMESPACE_BEGIN

// only to pass cmake on windows
void func();

SERVER_TEMPLATE_NAMESPACE_END

#endif // !SERVER_TEMPLATE_NS_H_