#ifndef SERVER_TEMPLATE_TCP_TCP_CONNECTION_HANDLER_H_
#define SERVER_TEMPLATE_TCP_TCP_CONNECTION_HANDLER_H_

#include "tcp_ns.h"
#include <uv.h>

SERVER_TEMPLATE_TCP_NAMESPACE_BEGIN

class TCPConnectionHandler : public uv_tcp_t
{

};

SERVER_TEMPLATE_TCP_NAMESPACE_END

#endif // !SERVER_TEMPLATE_TCP_TCP_CONNECTION_HANDLER_H_