#ifndef SERVER_TEMPLATE_TCP_NS_H_
#define SERVER_TEMPLATE_TCP_NS_H_

#include "../server_template_ns.h"

#ifndef SERVER_TEMPLATE_TCP_NAMESPACE
#define SERVER_TEMPLATE_TCP_NAMESPACE tcp
#endif // !SERVER_TEMPLATE_TCP_NAMESPACE

#ifndef SERVER_TEMPLATE_TCP_NAMESPACE_BEGIN
#define SERVER_TEMPLATE_TCP_NAMESPACE_BEGIN SERVER_TEMPLATE_NAMESPACE_BEGIN namespace SERVER_TEMPLATE_TCP_NAMESPACE {
#endif // !SERVER_TEMPLATE_TCP_NAMESPACE_BEGIN

#ifndef SERVER_TEMPLATE_TCP_NAMESPACE_END
#define SERVER_TEMPLATE_TCP_NAMESPACE_END SERVER_TEMPLATE_NAMESPACE_END }
#endif // !SERVER_TEMPLATE_TCP_NAMESPACE_END

#endif // !SERVER_TEMPLATE_TCP_NS_H_